-- 0031: catálogo completo de ejercicios (126 ejercicios).
-- GENERADO por scripts/generate-exercise-sql.mjs desde src/data/exercises.ts.
-- Upsert: actualiza los existentes (incluye taxonomía de hombros front/lateral/rear_delt)
-- e inserta los nuevos.
insert into public.exercises (id, name, muscle_group, equipment, is_compound, instructions) values
  ('bench-press', 'Press de banca', 'chest', 'barbell', true, 'Acuéstate en banca, baja la barra al pecho y empuja hasta extender los codos.'),
  ('incline-bench-press', 'Press inclinado con barra', 'chest', 'barbell', true, 'Banca a 30–45°, baja la barra a la parte alta del pecho y empuja.'),
  ('decline-bench-press', 'Press declinado con barra', 'chest', 'barbell', true, 'Banca declinada, baja la barra a la parte baja del pecho y empuja.'),
  ('incline-db-press', 'Press inclinado con mancuernas', 'chest', 'dumbbell', true, 'Banca a 30°, baja las mancuernas controladas hasta el pecho.'),
  ('flat-db-press', 'Press plano con mancuernas', 'chest', 'dumbbell', true, 'Acostado en banca plana, baja las mancuernas al pecho y empuja arriba.'),
  ('decline-db-press', 'Press declinado con mancuernas', 'chest', 'dumbbell', true, 'Banca declinada, empuja las mancuernas desde la parte baja del pecho.'),
  ('smith-bench-press', 'Press de banca en Smith', 'chest', 'smith', true, 'En máquina Smith, baja la barra al pecho con trayectoria guiada y empuja.'),
  ('chest-press-machine', 'Press de pecho en máquina', 'chest', 'machine', true, 'Espalda apoyada, empuja las agarraderas al frente sin bloquear codos.'),
  ('db-fly', 'Aperturas con mancuernas', 'chest', 'dumbbell', false, 'Acostado, abre los brazos semiflexionados y junta las mancuernas arriba.'),
  ('incline-db-fly', 'Aperturas inclinadas con mancuernas', 'chest', 'dumbbell', false, 'Banca a 30°, abre los brazos y junta las mancuernas sobre el pecho alto.'),
  ('cable-fly', 'Aperturas con cable', 'chest', 'cable', false, 'Brazos ligeramente flexionados, junta las manos al frente.'),
  ('cable-crossover', 'Cruce de poleas', 'chest', 'cable', false, 'Poleas altas, lleva las manos abajo y al frente cruzando ligeramente.'),
  ('low-cable-fly', 'Aperturas en polea baja', 'chest', 'cable', false, 'Poleas bajas, eleva las manos al frente hasta la altura del pecho.'),
  ('pec-deck', 'Contractora (pec deck)', 'chest', 'machine', false, 'Junta los brazos al frente apretando el pecho, vuelve controlado.'),
  ('push-up', 'Flexiones', 'chest', 'bodyweight', true, 'Cuerpo recto, baja el pecho al suelo y empuja hasta extender los brazos.'),
  ('chest-dips', 'Fondos en paralelas (pecho)', 'chest', 'bodyweight', true, 'Inclina el torso adelante, baja controlado y empuja hasta arriba.'),
  ('pull-up', 'Dominadas', 'back', 'bodyweight', true, 'Cuelga, sube hasta superar la barra con la barbilla.'),
  ('chin-up', 'Dominadas supinas', 'back', 'bodyweight', true, 'Agarre supino al ancho de hombros, sube el pecho hacia la barra.'),
  ('assisted-pull-up', 'Dominadas asistidas', 'back', 'machine', true, 'Apoya las rodillas en la plataforma y sube como en una dominada.'),
  ('inverted-row', 'Remo invertido', 'back', 'bodyweight', true, 'Bajo una barra fija, cuerpo recto, tira del pecho hacia la barra.'),
  ('barbell-row', 'Remo con barra', 'back', 'barbell', true, 'Espalda neutra, tira la barra hacia el abdomen.'),
  ('pendlay-row', 'Remo Pendlay', 'back', 'barbell', true, 'Torso paralelo al suelo, tira la barra desde el suelo al pecho en cada rep.'),
  ('t-bar-row', 'Remo en T', 'back', 'barbell', true, 'Inclinado sobre la barra T, tira del agarre hacia el pecho.'),
  ('single-arm-db-row', 'Remo con mancuerna a una mano', 'back', 'dumbbell', true, 'Apoya rodilla y mano en banca, tira la mancuerna hacia la cadera.'),
  ('chest-supported-row', 'Remo con apoyo en banca', 'back', 'dumbbell', true, 'Pecho apoyado en banca inclinada, rema con ambas mancuernas.'),
  ('seated-cable-row', 'Remo sentado en polea', 'back', 'cable', true, 'Sentado, tira del agarre al abdomen con la espalda neutra.'),
  ('machine-row', 'Remo en máquina', 'back', 'machine', true, 'Pecho apoyado, tira de las agarraderas hacia atrás juntando escápulas.'),
  ('lat-pulldown', 'Jalón al pecho', 'back', 'cable', true, 'Tira la barra hacia el pecho, codos abajo.'),
  ('close-grip-lat-pulldown', 'Jalón agarre cerrado', 'back', 'cable', true, 'Agarre neutro cerrado, tira hacia el pecho llevando los codos al torso.'),
  ('straight-arm-pulldown', 'Pullover en polea', 'back', 'cable', false, 'Brazos rectos, lleva la barra de arriba hacia los muslos.'),
  ('db-pullover', 'Pullover con mancuerna', 'back', 'dumbbell', false, 'Acostado, baja la mancuerna detrás de la cabeza y vuelve sobre el pecho.'),
  ('face-pull', 'Face pull', 'back', 'cable', false, 'Tira hacia la cara separando manos.'),
  ('back-extension', 'Hiperextensiones', 'back', 'bodyweight', false, 'En banco romano, baja el torso y sube hasta alinear con las piernas.'),
  ('rack-pull', 'Rack pull', 'back', 'barbell', true, 'Peso muerto parcial desde soportes a la altura de las rodillas.'),
  ('barbell-shrug', 'Encogimientos con barra', 'back', 'barbell', false, 'Eleva los hombros hacia las orejas, pausa arriba y baja controlado.'),
  ('db-shrug', 'Encogimientos con mancuernas', 'back', 'dumbbell', false, 'Mancuernas a los lados, encoge los hombros sin flexionar los codos.'),
  ('overhead-press', 'Press militar', 'front_delt', 'barbell', true, 'Empuja la barra encima de la cabeza, glúteos contraídos.'),
  ('seated-db-shoulder-press', 'Press de hombros con mancuernas', 'front_delt', 'dumbbell', true, 'Sentado, empuja las mancuernas desde los hombros hasta arriba.'),
  ('arnold-press', 'Press Arnold', 'front_delt', 'dumbbell', true, 'Inicia con palmas hacia ti, rota mientras empujas arriba.'),
  ('machine-shoulder-press', 'Press de hombros en máquina', 'front_delt', 'machine', true, 'Espalda apoyada, empuja las agarraderas sobre la cabeza.'),
  ('smith-shoulder-press', 'Press militar en Smith', 'front_delt', 'smith', true, 'Sentado bajo la barra guiada, empuja sobre la cabeza.'),
  ('push-press', 'Push press', 'front_delt', 'barbell', true, 'Pequeño impulso de piernas y empuja la barra sobre la cabeza.'),
  ('landmine-press', 'Press landmine', 'front_delt', 'barbell', true, 'Barra anclada al suelo, empuja el extremo arriba y al frente.'),
  ('front-raise', 'Elevaciones frontales', 'front_delt', 'dumbbell', false, 'Eleva las mancuernas al frente hasta la altura de los hombros.'),
  ('lateral-raise', 'Elevaciones laterales', 'lateral_delt', 'dumbbell', false, 'Eleva mancuernas a los lados hasta altura de hombros.'),
  ('cable-lateral-raise', 'Elevaciones laterales en polea', 'lateral_delt', 'cable', false, 'Polea baja, eleva el brazo al lado con tensión constante.'),
  ('machine-lateral-raise', 'Elevaciones laterales en máquina', 'lateral_delt', 'machine', false, 'Codos contra las almohadillas, eleva hasta la altura de hombros.'),
  ('upright-row', 'Remo al mentón', 'lateral_delt', 'barbell', true, 'Tira la barra hacia la barbilla con los codos por encima de las manos.'),
  ('rear-delt-fly', 'Pájaros (rear delt)', 'rear_delt', 'dumbbell', false, 'Inclínate, eleva mancuernas hacia los lados.'),
  ('reverse-pec-deck', 'Contractora inversa', 'rear_delt', 'machine', false, 'De frente a la máquina, abre los brazos hacia atrás.'),
  ('cable-rear-delt-fly', 'Cruce posterior en polea', 'rear_delt', 'cable', false, 'Poleas cruzadas a la altura de la cara, abre los brazos hacia atrás.'),
  ('biceps-curl', 'Curl de bíceps', 'biceps', 'dumbbell', false, 'Codos pegados al torso, sube controlado.'),
  ('barbell-curl', 'Curl con barra', 'biceps', 'barbell', false, 'Agarre supino al ancho de hombros, sube la barra sin balancear.'),
  ('ez-bar-curl', 'Curl con barra EZ', 'biceps', 'barbell', false, 'Agarre en la curva de la barra EZ, sube con los codos fijos.'),
  ('hammer-curl', 'Curl martillo', 'biceps', 'dumbbell', false, 'Agarre neutro, sube hasta el hombro.'),
  ('incline-db-curl', 'Curl inclinado con mancuernas', 'biceps', 'dumbbell', false, 'En banca inclinada, brazos colgando, sube con máximo estiramiento.'),
  ('preacher-curl', 'Curl predicador', 'biceps', 'barbell', false, 'Brazos apoyados en el banco predicador, sube y baja controlado.'),
  ('concentration-curl', 'Curl concentrado', 'biceps', 'dumbbell', false, 'Sentado, codo apoyado en el muslo, sube la mancuerna al hombro.'),
  ('cable-curl', 'Curl en polea', 'biceps', 'cable', false, 'Polea baja, sube el agarre con tensión constante.'),
  ('machine-biceps-curl', 'Curl en máquina', 'biceps', 'machine', false, 'Brazos apoyados, flexiona los codos contra la resistencia.'),
  ('spider-curl', 'Curl araña', 'biceps', 'dumbbell', false, 'Pecho apoyado en banca inclinada, brazos verticales, sube las mancuernas.'),
  ('reverse-curl', 'Curl inverso', 'biceps', 'barbell', false, 'Agarre prono, sube la barra manteniendo las muñecas firmes.'),
  ('triceps-pushdown', 'Press tríceps polea', 'triceps', 'cable', false, 'Codos pegados al torso, extiende los brazos.'),
  ('rope-pushdown', 'Extensión con cuerda en polea', 'triceps', 'cable', false, 'Extiende los brazos separando la cuerda al final del movimiento.'),
  ('skull-crusher', 'Skull crusher', 'triceps', 'barbell', false, 'Acostado, baja la barra a la frente flexionando codos.'),
  ('close-grip-bench-press', 'Press banca agarre cerrado', 'triceps', 'barbell', true, 'Manos al ancho de hombros, baja la barra al pecho con codos cerrados.'),
  ('overhead-cable-extension', 'Extensión de tríceps en polea sobre cabeza', 'triceps', 'cable', false, 'De espaldas a la polea, extiende los brazos sobre la cabeza.'),
  ('overhead-db-extension', 'Extensión con mancuerna sobre cabeza', 'triceps', 'dumbbell', false, 'Sujeta una mancuerna con ambas manos detrás de la cabeza y extiende.'),
  ('triceps-kickback', 'Patada de tríceps', 'triceps', 'dumbbell', false, 'Torso inclinado, codo fijo, extiende el brazo hacia atrás.'),
  ('machine-triceps-extension', 'Extensión de tríceps en máquina', 'triceps', 'machine', false, 'Codos apoyados, extiende los brazos contra la resistencia.'),
  ('bench-dips', 'Fondos en banco', 'triceps', 'bodyweight', true, 'Manos en el banco detrás de ti, baja flexionando codos y empuja.'),
  ('diamond-push-up', 'Flexiones diamante', 'triceps', 'bodyweight', true, 'Manos juntas formando un diamante, baja el pecho y empuja.'),
  ('squat', 'Sentadilla', 'quads', 'barbell', true, 'Baja caderas hasta paralelo, empuja el suelo.'),
  ('front-squat', 'Sentadilla frontal', 'quads', 'barbell', true, 'Barra sobre los hombros al frente, baja manteniendo el torso erguido.'),
  ('smith-squat', 'Sentadilla en Smith', 'quads', 'smith', true, 'Barra guiada sobre la espalda, baja controlado hasta paralelo.'),
  ('hack-squat', 'Sentadilla hack', 'quads', 'machine', true, 'Espalda apoyada en el respaldo, baja profundo y empuja con los talones.'),
  ('goblet-squat', 'Sentadilla goblet', 'quads', 'dumbbell', true, 'Mancuerna al pecho, baja entre las rodillas con el torso erguido.'),
  ('leg-press', 'Prensa de pierna', 'quads', 'machine', true, 'Pies a la altura del hombro, baja controlado.'),
  ('leg-extension', 'Extensión de cuádriceps', 'quads', 'machine', false, 'Extiende las rodillas contra la resistencia, pausa arriba.'),
  ('lunges', 'Zancadas', 'quads', 'dumbbell', true, 'Da un paso al frente y baja hasta 90°.'),
  ('walking-lunges', 'Zancadas caminando', 'quads', 'dumbbell', true, 'Avanza alternando zancadas, rodilla trasera cerca del suelo.'),
  ('bulgarian-split-squat', 'Sentadilla búlgara', 'quads', 'dumbbell', true, 'Pie trasero elevado en banca, baja vertical con la pierna delantera.'),
  ('step-up', 'Subida al cajón', 'quads', 'dumbbell', true, 'Sube al cajón empujando con la pierna de arriba, baja controlado.'),
  ('sissy-squat', 'Sentadilla sissy', 'quads', 'bodyweight', false, 'Inclínate hacia atrás flexionando rodillas, talones elevados.'),
  ('romanian-deadlift', 'Peso muerto rumano', 'hamstrings', 'barbell', true, 'Caderas atrás, baja con piernas casi rectas.'),
  ('db-romanian-deadlift', 'Peso muerto rumano con mancuernas', 'hamstrings', 'dumbbell', true, 'Mancuernas al frente, caderas atrás, baja por delante de las piernas.'),
  ('stiff-leg-deadlift', 'Peso muerto piernas rígidas', 'hamstrings', 'barbell', true, 'Piernas extendidas, baja la barra estirando los isquios al máximo.'),
  ('leg-curl', 'Curl femoral', 'hamstrings', 'machine', false, 'Flexiona las rodillas contra la resistencia.'),
  ('seated-leg-curl', 'Curl femoral sentado', 'hamstrings', 'machine', false, 'Sentado, flexiona las rodillas llevando los talones abajo y atrás.'),
  ('good-morning', 'Buenos días', 'hamstrings', 'barbell', true, 'Barra en la espalda, inclina el torso con caderas atrás y sube.'),
  ('nordic-curl', 'Curl nórdico', 'hamstrings', 'bodyweight', false, 'Tobillos sujetos, baja el torso lo más lento posible.'),
  ('glute-ham-raise', 'Glute ham raise', 'hamstrings', 'machine', false, 'En banco GHD, baja el torso y sube flexionando las rodillas.'),
  ('hip-thrust', 'Hip thrust', 'glutes', 'barbell', true, 'Hombros sobre banco, eleva caderas contrayendo glúteo.'),
  ('machine-hip-thrust', 'Hip thrust en máquina', 'glutes', 'machine', true, 'Espalda apoyada, empuja la plataforma con las caderas hacia arriba.'),
  ('glute-bridge', 'Puente de glúteos', 'glutes', 'bodyweight', false, 'Acostado, eleva las caderas apretando glúteos, pausa arriba.'),
  ('sumo-deadlift', 'Peso muerto sumo', 'glutes', 'barbell', true, 'Postura ancha, agarre por dentro de las rodillas, levanta con caderas.'),
  ('cable-kickback', 'Patada de glúteo en polea', 'glutes', 'cable', false, 'Tobillera en polea baja, extiende la pierna hacia atrás.'),
  ('cable-pull-through', 'Pull through en polea', 'glutes', 'cable', false, 'De espaldas a la polea baja, bisagra de cadera y extiende apretando glúteo.'),
  ('hip-abduction-machine', 'Abducción de cadera en máquina', 'glutes', 'machine', false, 'Sentado, abre las piernas contra la resistencia y vuelve controlado.'),
  ('standing-calf', 'Elevación de gemelos', 'calves', 'machine', false, 'Eleva los talones al máximo, contracción de 1s.'),
  ('seated-calf-raise', 'Elevación de gemelos sentado', 'calves', 'machine', false, 'Sentado con peso en las rodillas, eleva los talones y baja profundo.'),
  ('calf-press', 'Gemelos en prensa', 'calves', 'machine', false, 'En la prensa, empuja con la punta de los pies extendiendo tobillos.'),
  ('smith-calf-raise', 'Gemelos en Smith', 'calves', 'smith', false, 'Barra guiada en la espalda, puntas en un escalón, eleva talones.'),
  ('single-leg-calf-raise', 'Gemelos a una pierna', 'calves', 'bodyweight', false, 'A una pierna en un escalón, sube al máximo y baja profundo.'),
  ('plank', 'Plancha', 'core', 'bodyweight', false, 'Mantén el cuerpo recto, abdomen contraído.'),
  ('side-plank', 'Plancha lateral', 'core', 'bodyweight', false, 'De lado sobre el antebrazo, cadera elevada y cuerpo en línea.'),
  ('hanging-leg-raise', 'Elevación de piernas colgado', 'core', 'bodyweight', false, 'Cuelga y eleva las piernas controladas.'),
  ('lying-leg-raise', 'Elevación de piernas en suelo', 'core', 'bodyweight', false, 'Acostado, eleva las piernas rectas y baja sin tocar el suelo.'),
  ('crunch', 'Crunch abdominal', 'core', 'bodyweight', false, 'Acostado, eleva los hombros contrayendo el abdomen.'),
  ('bicycle-crunch', 'Crunch bicicleta', 'core', 'bodyweight', false, 'Alterna codo con rodilla contraria pedaleando en el aire.'),
  ('decline-sit-up', 'Sit-up declinado', 'core', 'bodyweight', false, 'En banca declinada, sube el torso completo y baja controlado.'),
  ('cable-crunch', 'Crunch en polea', 'core', 'cable', false, 'De rodillas frente a la polea alta, flexiona el torso hacia abajo.'),
  ('machine-crunch', 'Crunch en máquina', 'core', 'machine', false, 'Flexiona el torso contra la resistencia, exhala al contraer.'),
  ('russian-twist', 'Giros rusos', 'core', 'bodyweight', false, 'Sentado con el torso atrás, gira de lado a lado con control.'),
  ('mountain-climbers', 'Escaladores', 'core', 'bodyweight', false, 'En plancha alta, lleva las rodillas al pecho alternando rápido.'),
  ('dead-bug', 'Dead bug', 'core', 'bodyweight', false, 'Boca arriba, extiende brazo y pierna contrarios sin arquear la espalda.'),
  ('ab-wheel', 'Rueda abdominal', 'core', 'bodyweight', false, 'De rodillas, rueda al frente manteniendo el abdomen firme y vuelve.'),
  ('pallof-press', 'Press Pallof', 'core', 'cable', false, 'De lado a la polea, extiende los brazos al frente resistiendo el giro.'),
  ('deadlift', 'Peso muerto', 'full_body', 'barbell', true, 'Caderas atrás, espalda neutra, levanta empujando el suelo.'),
  ('trap-bar-deadlift', 'Peso muerto con barra hexagonal', 'full_body', 'barbell', true, 'Dentro de la barra hexagonal, levanta con espalda neutra.'),
  ('clean-and-press', 'Cargada y press', 'full_body', 'barbell', true, 'Lleva la barra del suelo a los hombros y empuja sobre la cabeza.'),
  ('thruster', 'Thruster', 'full_body', 'barbell', true, 'Sentadilla frontal y al subir empuja la barra sobre la cabeza.'),
  ('kettlebell-swing', 'Swing con kettlebell', 'full_body', 'kettlebell', true, 'Bisagra de cadera, impulsa la kettlebell hasta la altura del pecho.'),
  ('turkish-getup', 'Levantamiento turco', 'full_body', 'kettlebell', true, 'Del suelo a de pie con la kettlebell siempre sobre la cabeza.'),
  ('farmers-walk', 'Paseo del granjero', 'full_body', 'dumbbell', true, 'Camina erguido cargando peso pesado en ambas manos.'),
  ('burpee', 'Burpees', 'full_body', 'bodyweight', true, 'Flexión, salto de pies al pecho y salto vertical, encadenado.')
on conflict (id) do update set
  name = excluded.name,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  is_compound = excluded.is_compound,
  instructions = excluded.instructions;
