-- 0032: catálogo ampliado de ejercicios (212 ejercicios).
-- GENERADO por scripts/generate-exercise-sql.mjs desde src/data/exercises.ts.
-- Upsert idempotente: persiste secondary_muscles e inserta los ejercicios nuevos
-- sin tocar los existentes (no hay DELETE → no rompe FKs de rutinas).
insert into public.exercises (id, name, muscle_group, secondary_muscles, equipment, is_compound, instructions) values
  ('bench-press', 'Press de banca', 'chest', array['triceps', 'front_delt']::text[], 'barbell', true, 'Acuéstate en banca, baja la barra al pecho y empuja hasta extender los codos.'),
  ('incline-bench-press', 'Press inclinado con barra', 'chest', array['front_delt', 'triceps']::text[], 'barbell', true, 'Banca a 30–45°, baja la barra a la parte alta del pecho y empuja.'),
  ('decline-bench-press', 'Press declinado con barra', 'chest', array['triceps', 'front_delt']::text[], 'barbell', true, 'Banca declinada, baja la barra a la parte baja del pecho y empuja.'),
  ('incline-db-press', 'Press inclinado con mancuernas', 'chest', array['front_delt', 'triceps']::text[], 'dumbbell', true, 'Banca a 30°, baja las mancuernas controladas hasta el pecho.'),
  ('flat-db-press', 'Press plano con mancuernas', 'chest', array['triceps', 'front_delt']::text[], 'dumbbell', true, 'Acostado en banca plana, baja las mancuernas al pecho y empuja arriba.'),
  ('decline-db-press', 'Press declinado con mancuernas', 'chest', array['triceps', 'front_delt']::text[], 'dumbbell', true, 'Banca declinada, empuja las mancuernas desde la parte baja del pecho.'),
  ('smith-bench-press', 'Press de banca en Smith', 'chest', array['triceps', 'front_delt']::text[], 'smith', true, 'En máquina Smith, baja la barra al pecho con trayectoria guiada y empuja.'),
  ('chest-press-machine', 'Press de pecho en máquina', 'chest', array['triceps', 'front_delt']::text[], 'machine', true, 'Espalda apoyada, empuja las agarraderas al frente sin bloquear codos.'),
  ('db-fly', 'Aperturas con mancuernas', 'chest', '{}'::text[], 'dumbbell', false, 'Acostado, abre los brazos semiflexionados y junta las mancuernas arriba.'),
  ('incline-db-fly', 'Aperturas inclinadas con mancuernas', 'chest', '{}'::text[], 'dumbbell', false, 'Banca a 30°, abre los brazos y junta las mancuernas sobre el pecho alto.'),
  ('cable-fly', 'Aperturas con cable', 'chest', '{}'::text[], 'cable', false, 'Brazos ligeramente flexionados, junta las manos al frente.'),
  ('cable-crossover', 'Cruce de poleas', 'chest', '{}'::text[], 'cable', false, 'Poleas altas, lleva las manos abajo y al frente cruzando ligeramente.'),
  ('low-cable-fly', 'Aperturas en polea baja', 'chest', '{}'::text[], 'cable', false, 'Poleas bajas, eleva las manos al frente hasta la altura del pecho.'),
  ('pec-deck', 'Contractora (pec deck)', 'chest', '{}'::text[], 'machine', false, 'Junta los brazos al frente apretando el pecho, vuelve controlado.'),
  ('push-up', 'Flexiones', 'chest', array['triceps', 'front_delt']::text[], 'bodyweight', true, 'Cuerpo recto, baja el pecho al suelo y empuja hasta extender los brazos.'),
  ('chest-dips', 'Fondos en paralelas (pecho)', 'chest', array['triceps', 'front_delt']::text[], 'bodyweight', true, 'Inclina el torso adelante, baja controlado y empuja hasta arriba.'),
  ('pull-up', 'Dominadas', 'back', array['biceps', 'rear_delt']::text[], 'bodyweight', true, 'Cuelga, sube hasta superar la barra con la barbilla.'),
  ('chin-up', 'Dominadas supinas', 'back', array['biceps', 'rear_delt']::text[], 'bodyweight', true, 'Agarre supino al ancho de hombros, sube el pecho hacia la barra.'),
  ('assisted-pull-up', 'Dominadas asistidas', 'back', array['biceps', 'rear_delt']::text[], 'machine', true, 'Apoya las rodillas en la plataforma y sube como en una dominada.'),
  ('inverted-row', 'Remo invertido', 'back', array['biceps', 'rear_delt']::text[], 'bodyweight', true, 'Bajo una barra fija, cuerpo recto, tira del pecho hacia la barra.'),
  ('barbell-row', 'Remo con barra', 'back', array['biceps', 'rear_delt']::text[], 'barbell', true, 'Espalda neutra, tira la barra hacia el abdomen.'),
  ('pendlay-row', 'Remo Pendlay', 'back', array['biceps', 'rear_delt']::text[], 'barbell', true, 'Torso paralelo al suelo, tira la barra desde el suelo al pecho en cada rep.'),
  ('t-bar-row', 'Remo en T', 'back', array['biceps', 'rear_delt']::text[], 'barbell', true, 'Inclinado sobre la barra T, tira del agarre hacia el pecho.'),
  ('single-arm-db-row', 'Remo con mancuerna a una mano', 'back', array['biceps', 'rear_delt']::text[], 'dumbbell', true, 'Apoya rodilla y mano en banca, tira la mancuerna hacia la cadera.'),
  ('chest-supported-row', 'Remo con apoyo en banca', 'back', array['biceps', 'rear_delt']::text[], 'dumbbell', true, 'Pecho apoyado en banca inclinada, rema con ambas mancuernas.'),
  ('seated-cable-row', 'Remo sentado en polea', 'back', array['biceps', 'rear_delt']::text[], 'cable', true, 'Sentado, tira del agarre al abdomen con la espalda neutra.'),
  ('machine-row', 'Remo en máquina', 'back', array['biceps', 'rear_delt']::text[], 'machine', true, 'Pecho apoyado, tira de las agarraderas hacia atrás juntando escápulas.'),
  ('lat-pulldown', 'Jalón al pecho', 'back', array['biceps', 'rear_delt']::text[], 'cable', true, 'Tira la barra hacia el pecho, codos abajo.'),
  ('close-grip-lat-pulldown', 'Jalón agarre cerrado', 'back', array['biceps', 'rear_delt']::text[], 'cable', true, 'Agarre neutro cerrado, tira hacia el pecho llevando los codos al torso.'),
  ('straight-arm-pulldown', 'Pullover en polea', 'back', array['triceps']::text[], 'cable', false, 'Brazos rectos, lleva la barra de arriba hacia los muslos.'),
  ('db-pullover', 'Pullover con mancuerna', 'back', array['chest', 'triceps']::text[], 'dumbbell', false, 'Acostado, baja la mancuerna detrás de la cabeza y vuelve sobre el pecho.'),
  ('face-pull', 'Face pull', 'back', array['rear_delt']::text[], 'cable', false, 'Tira hacia la cara separando manos.'),
  ('back-extension', 'Hiperextensiones', 'back', array['glutes', 'hamstrings']::text[], 'bodyweight', false, 'En banco romano, baja el torso y sube hasta alinear con las piernas.'),
  ('rack-pull', 'Rack pull', 'back', array['hamstrings', 'glutes']::text[], 'barbell', true, 'Peso muerto parcial desde soportes a la altura de las rodillas.'),
  ('barbell-shrug', 'Encogimientos con barra', 'back', '{}'::text[], 'barbell', false, 'Eleva los hombros hacia las orejas, pausa arriba y baja controlado.'),
  ('db-shrug', 'Encogimientos con mancuernas', 'back', '{}'::text[], 'dumbbell', false, 'Mancuernas a los lados, encoge los hombros sin flexionar los codos.'),
  ('overhead-press', 'Press militar', 'front_delt', array['triceps', 'lateral_delt']::text[], 'barbell', true, 'Empuja la barra encima de la cabeza, glúteos contraídos.'),
  ('seated-db-shoulder-press', 'Press de hombros con mancuernas', 'front_delt', array['triceps', 'lateral_delt']::text[], 'dumbbell', true, 'Sentado, empuja las mancuernas desde los hombros hasta arriba.'),
  ('arnold-press', 'Press Arnold', 'front_delt', array['triceps', 'lateral_delt']::text[], 'dumbbell', true, 'Inicia con palmas hacia ti, rota mientras empujas arriba.'),
  ('machine-shoulder-press', 'Press de hombros en máquina', 'front_delt', array['triceps', 'lateral_delt']::text[], 'machine', true, 'Espalda apoyada, empuja las agarraderas sobre la cabeza.'),
  ('smith-shoulder-press', 'Press militar en Smith', 'front_delt', array['triceps', 'lateral_delt']::text[], 'smith', true, 'Sentado bajo la barra guiada, empuja sobre la cabeza.'),
  ('push-press', 'Push press', 'front_delt', array['triceps', 'lateral_delt']::text[], 'barbell', true, 'Pequeño impulso de piernas y empuja la barra sobre la cabeza.'),
  ('landmine-press', 'Press landmine', 'front_delt', array['triceps', 'chest']::text[], 'barbell', true, 'Barra anclada al suelo, empuja el extremo arriba y al frente.'),
  ('front-raise', 'Elevaciones frontales', 'front_delt', '{}'::text[], 'dumbbell', false, 'Eleva las mancuernas al frente hasta la altura de los hombros.'),
  ('lateral-raise', 'Elevaciones laterales', 'lateral_delt', '{}'::text[], 'dumbbell', false, 'Eleva mancuernas a los lados hasta altura de hombros.'),
  ('cable-lateral-raise', 'Elevaciones laterales en polea', 'lateral_delt', '{}'::text[], 'cable', false, 'Polea baja, eleva el brazo al lado con tensión constante.'),
  ('machine-lateral-raise', 'Elevaciones laterales en máquina', 'lateral_delt', '{}'::text[], 'machine', false, 'Codos contra las almohadillas, eleva hasta la altura de hombros.'),
  ('upright-row', 'Remo al mentón', 'lateral_delt', array['front_delt', 'back']::text[], 'barbell', true, 'Tira la barra hacia la barbilla con los codos por encima de las manos.'),
  ('rear-delt-fly', 'Pájaros (rear delt)', 'rear_delt', '{}'::text[], 'dumbbell', false, 'Inclínate, eleva mancuernas hacia los lados.'),
  ('reverse-pec-deck', 'Contractora inversa', 'rear_delt', array['back']::text[], 'machine', false, 'De frente a la máquina, abre los brazos hacia atrás.'),
  ('cable-rear-delt-fly', 'Cruce posterior en polea', 'rear_delt', '{}'::text[], 'cable', false, 'Poleas cruzadas a la altura de la cara, abre los brazos hacia atrás.'),
  ('biceps-curl', 'Curl de bíceps', 'biceps', '{}'::text[], 'dumbbell', false, 'Codos pegados al torso, sube controlado.'),
  ('barbell-curl', 'Curl con barra', 'biceps', '{}'::text[], 'barbell', false, 'Agarre supino al ancho de hombros, sube la barra sin balancear.'),
  ('ez-bar-curl', 'Curl con barra EZ', 'biceps', '{}'::text[], 'barbell', false, 'Agarre en la curva de la barra EZ, sube con los codos fijos.'),
  ('hammer-curl', 'Curl martillo', 'biceps', '{}'::text[], 'dumbbell', false, 'Agarre neutro, sube hasta el hombro.'),
  ('incline-db-curl', 'Curl inclinado con mancuernas', 'biceps', '{}'::text[], 'dumbbell', false, 'En banca inclinada, brazos colgando, sube con máximo estiramiento.'),
  ('preacher-curl', 'Curl predicador', 'biceps', '{}'::text[], 'barbell', false, 'Brazos apoyados en el banco predicador, sube y baja controlado.'),
  ('concentration-curl', 'Curl concentrado', 'biceps', '{}'::text[], 'dumbbell', false, 'Sentado, codo apoyado en el muslo, sube la mancuerna al hombro.'),
  ('cable-curl', 'Curl en polea', 'biceps', '{}'::text[], 'cable', false, 'Polea baja, sube el agarre con tensión constante.'),
  ('machine-biceps-curl', 'Curl en máquina', 'biceps', '{}'::text[], 'machine', false, 'Brazos apoyados, flexiona los codos contra la resistencia.'),
  ('spider-curl', 'Curl araña', 'biceps', '{}'::text[], 'dumbbell', false, 'Pecho apoyado en banca inclinada, brazos verticales, sube las mancuernas.'),
  ('reverse-curl', 'Curl inverso', 'biceps', '{}'::text[], 'barbell', false, 'Agarre prono, sube la barra manteniendo las muñecas firmes.'),
  ('triceps-pushdown', 'Press tríceps polea', 'triceps', '{}'::text[], 'cable', false, 'Codos pegados al torso, extiende los brazos.'),
  ('rope-pushdown', 'Extensión con cuerda en polea', 'triceps', '{}'::text[], 'cable', false, 'Extiende los brazos separando la cuerda al final del movimiento.'),
  ('skull-crusher', 'Skull crusher', 'triceps', '{}'::text[], 'barbell', false, 'Acostado, baja la barra a la frente flexionando codos.'),
  ('close-grip-bench-press', 'Press banca agarre cerrado', 'triceps', array['chest', 'front_delt']::text[], 'barbell', true, 'Manos al ancho de hombros, baja la barra al pecho con codos cerrados.'),
  ('overhead-cable-extension', 'Extensión de tríceps en polea sobre cabeza', 'triceps', '{}'::text[], 'cable', false, 'De espaldas a la polea, extiende los brazos sobre la cabeza.'),
  ('overhead-db-extension', 'Extensión con mancuerna sobre cabeza', 'triceps', '{}'::text[], 'dumbbell', false, 'Sujeta una mancuerna con ambas manos detrás de la cabeza y extiende.'),
  ('triceps-kickback', 'Patada de tríceps', 'triceps', '{}'::text[], 'dumbbell', false, 'Torso inclinado, codo fijo, extiende el brazo hacia atrás.'),
  ('machine-triceps-extension', 'Extensión de tríceps en máquina', 'triceps', '{}'::text[], 'machine', false, 'Codos apoyados, extiende los brazos contra la resistencia.'),
  ('bench-dips', 'Fondos en banco', 'triceps', array['chest', 'front_delt']::text[], 'bodyweight', true, 'Manos en el banco detrás de ti, baja flexionando codos y empuja.'),
  ('diamond-push-up', 'Flexiones diamante', 'triceps', array['chest', 'front_delt']::text[], 'bodyweight', true, 'Manos juntas formando un diamante, baja el pecho y empuja.'),
  ('squat', 'Sentadilla', 'quads', array['glutes', 'hamstrings']::text[], 'barbell', true, 'Baja caderas hasta paralelo, empuja el suelo.'),
  ('front-squat', 'Sentadilla frontal', 'quads', array['glutes', 'core']::text[], 'barbell', true, 'Barra sobre los hombros al frente, baja manteniendo el torso erguido.'),
  ('smith-squat', 'Sentadilla en Smith', 'quads', array['glutes', 'hamstrings']::text[], 'smith', true, 'Barra guiada sobre la espalda, baja controlado hasta paralelo.'),
  ('hack-squat', 'Sentadilla hack', 'quads', array['glutes', 'hamstrings']::text[], 'machine', true, 'Espalda apoyada en el respaldo, baja profundo y empuja con los talones.'),
  ('goblet-squat', 'Sentadilla goblet', 'quads', array['glutes', 'hamstrings']::text[], 'dumbbell', true, 'Mancuerna al pecho, baja entre las rodillas con el torso erguido.'),
  ('leg-press', 'Prensa de pierna', 'quads', array['glutes', 'hamstrings']::text[], 'machine', true, 'Pies a la altura del hombro, baja controlado.'),
  ('leg-extension', 'Extensión de cuádriceps', 'quads', '{}'::text[], 'machine', false, 'Extiende las rodillas contra la resistencia, pausa arriba.'),
  ('lunges', 'Zancadas', 'quads', array['glutes', 'hamstrings']::text[], 'dumbbell', true, 'Da un paso al frente y baja hasta 90°.'),
  ('walking-lunges', 'Zancadas caminando', 'quads', array['glutes', 'hamstrings']::text[], 'dumbbell', true, 'Avanza alternando zancadas, rodilla trasera cerca del suelo.'),
  ('bulgarian-split-squat', 'Sentadilla búlgara', 'quads', array['glutes', 'hamstrings']::text[], 'dumbbell', true, 'Pie trasero elevado en banca, baja vertical con la pierna delantera.'),
  ('step-up', 'Subida al cajón', 'quads', array['glutes', 'hamstrings']::text[], 'dumbbell', true, 'Sube al cajón empujando con la pierna de arriba, baja controlado.'),
  ('sissy-squat', 'Sentadilla sissy', 'quads', '{}'::text[], 'bodyweight', false, 'Inclínate hacia atrás flexionando rodillas, talones elevados.'),
  ('romanian-deadlift', 'Peso muerto rumano', 'hamstrings', array['glutes', 'back']::text[], 'barbell', true, 'Caderas atrás, baja con piernas casi rectas.'),
  ('db-romanian-deadlift', 'Peso muerto rumano con mancuernas', 'hamstrings', array['glutes', 'back']::text[], 'dumbbell', true, 'Mancuernas al frente, caderas atrás, baja por delante de las piernas.'),
  ('stiff-leg-deadlift', 'Peso muerto piernas rígidas', 'hamstrings', array['glutes', 'back']::text[], 'barbell', true, 'Piernas extendidas, baja la barra estirando los isquios al máximo.'),
  ('leg-curl', 'Curl femoral', 'hamstrings', '{}'::text[], 'machine', false, 'Flexiona las rodillas contra la resistencia.'),
  ('seated-leg-curl', 'Curl femoral sentado', 'hamstrings', '{}'::text[], 'machine', false, 'Sentado, flexiona las rodillas llevando los talones abajo y atrás.'),
  ('good-morning', 'Buenos días', 'hamstrings', array['glutes', 'back']::text[], 'barbell', true, 'Barra en la espalda, inclina el torso con caderas atrás y sube.'),
  ('nordic-curl', 'Curl nórdico', 'hamstrings', '{}'::text[], 'bodyweight', false, 'Tobillos sujetos, baja el torso lo más lento posible.'),
  ('glute-ham-raise', 'Glute ham raise', 'hamstrings', array['glutes']::text[], 'machine', false, 'En banco GHD, baja el torso y sube flexionando las rodillas.'),
  ('hip-thrust', 'Hip thrust', 'glutes', array['hamstrings']::text[], 'barbell', true, 'Hombros sobre banco, eleva caderas contrayendo glúteo.'),
  ('machine-hip-thrust', 'Hip thrust en máquina', 'glutes', array['hamstrings']::text[], 'machine', true, 'Espalda apoyada, empuja la plataforma con las caderas hacia arriba.'),
  ('glute-bridge', 'Puente de glúteos', 'glutes', array['hamstrings']::text[], 'bodyweight', false, 'Acostado, eleva las caderas apretando glúteos, pausa arriba.'),
  ('sumo-deadlift', 'Peso muerto sumo', 'glutes', array['quads', 'hamstrings', 'back']::text[], 'barbell', true, 'Postura ancha, agarre por dentro de las rodillas, levanta con caderas.'),
  ('cable-kickback', 'Patada de glúteo en polea', 'glutes', array['hamstrings']::text[], 'cable', false, 'Tobillera en polea baja, extiende la pierna hacia atrás.'),
  ('cable-pull-through', 'Pull through en polea', 'glutes', array['hamstrings', 'back']::text[], 'cable', false, 'De espaldas a la polea baja, bisagra de cadera y extiende apretando glúteo.'),
  ('hip-abduction-machine', 'Abducción de cadera en máquina', 'glutes', '{}'::text[], 'machine', false, 'Sentado, abre las piernas contra la resistencia y vuelve controlado.'),
  ('standing-calf', 'Elevación de gemelos', 'calves', '{}'::text[], 'machine', false, 'Eleva los talones al máximo, contracción de 1s.'),
  ('seated-calf-raise', 'Elevación de gemelos sentado', 'calves', '{}'::text[], 'machine', false, 'Sentado con peso en las rodillas, eleva los talones y baja profundo.'),
  ('calf-press', 'Gemelos en prensa', 'calves', '{}'::text[], 'machine', false, 'En la prensa, empuja con la punta de los pies extendiendo tobillos.'),
  ('smith-calf-raise', 'Gemelos en Smith', 'calves', '{}'::text[], 'smith', false, 'Barra guiada en la espalda, puntas en un escalón, eleva talones.'),
  ('single-leg-calf-raise', 'Gemelos a una pierna', 'calves', '{}'::text[], 'bodyweight', false, 'A una pierna en un escalón, sube al máximo y baja profundo.'),
  ('plank', 'Plancha', 'core', '{}'::text[], 'bodyweight', false, 'Mantén el cuerpo recto, abdomen contraído.'),
  ('side-plank', 'Plancha lateral', 'core', '{}'::text[], 'bodyweight', false, 'De lado sobre el antebrazo, cadera elevada y cuerpo en línea.'),
  ('hanging-leg-raise', 'Elevación de piernas colgado', 'core', '{}'::text[], 'bodyweight', false, 'Cuelga y eleva las piernas controladas.'),
  ('lying-leg-raise', 'Elevación de piernas en suelo', 'core', '{}'::text[], 'bodyweight', false, 'Acostado, eleva las piernas rectas y baja sin tocar el suelo.'),
  ('crunch', 'Crunch abdominal', 'core', '{}'::text[], 'bodyweight', false, 'Acostado, eleva los hombros contrayendo el abdomen.'),
  ('bicycle-crunch', 'Crunch bicicleta', 'core', '{}'::text[], 'bodyweight', false, 'Alterna codo con rodilla contraria pedaleando en el aire.'),
  ('decline-sit-up', 'Sit-up declinado', 'core', '{}'::text[], 'bodyweight', false, 'En banca declinada, sube el torso completo y baja controlado.'),
  ('cable-crunch', 'Crunch en polea', 'core', '{}'::text[], 'cable', false, 'De rodillas frente a la polea alta, flexiona el torso hacia abajo.'),
  ('machine-crunch', 'Crunch en máquina', 'core', '{}'::text[], 'machine', false, 'Flexiona el torso contra la resistencia, exhala al contraer.'),
  ('russian-twist', 'Giros rusos', 'core', '{}'::text[], 'bodyweight', false, 'Sentado con el torso atrás, gira de lado a lado con control.'),
  ('mountain-climbers', 'Escaladores', 'core', '{}'::text[], 'bodyweight', false, 'En plancha alta, lleva las rodillas al pecho alternando rápido.'),
  ('dead-bug', 'Dead bug', 'core', '{}'::text[], 'bodyweight', false, 'Boca arriba, extiende brazo y pierna contrarios sin arquear la espalda.'),
  ('ab-wheel', 'Rueda abdominal', 'core', '{}'::text[], 'bodyweight', false, 'De rodillas, rueda al frente manteniendo el abdomen firme y vuelve.'),
  ('pallof-press', 'Press Pallof', 'core', '{}'::text[], 'cable', false, 'De lado a la polea, extiende los brazos al frente resistiendo el giro.'),
  ('deadlift', 'Peso muerto', 'full_body', array['back', 'glutes', 'hamstrings', 'quads', 'core']::text[], 'barbell', true, 'Caderas atrás, espalda neutra, levanta empujando el suelo.'),
  ('trap-bar-deadlift', 'Peso muerto con barra hexagonal', 'full_body', array['back', 'glutes', 'hamstrings', 'quads', 'core']::text[], 'barbell', true, 'Dentro de la barra hexagonal, levanta con espalda neutra.'),
  ('clean-and-press', 'Cargada y press', 'full_body', array['back', 'glutes', 'hamstrings', 'front_delt', 'quads']::text[], 'barbell', true, 'Lleva la barra del suelo a los hombros y empuja sobre la cabeza.'),
  ('thruster', 'Thruster', 'full_body', array['quads', 'glutes', 'front_delt', 'triceps']::text[], 'barbell', true, 'Sentadilla frontal y al subir empuja la barra sobre la cabeza.'),
  ('kettlebell-swing', 'Swing con kettlebell', 'full_body', array['glutes', 'hamstrings', 'back', 'core']::text[], 'kettlebell', true, 'Bisagra de cadera, impulsa la kettlebell hasta la altura del pecho.'),
  ('turkish-getup', 'Levantamiento turco', 'full_body', array['core', 'front_delt', 'glutes']::text[], 'kettlebell', true, 'Del suelo a de pie con la kettlebell siempre sobre la cabeza.'),
  ('farmers-walk', 'Paseo del granjero', 'full_body', array['back', 'core']::text[], 'dumbbell', true, 'Camina erguido cargando peso pesado en ambas manos.'),
  ('burpee', 'Burpees', 'full_body', array['chest', 'quads', 'core']::text[], 'bodyweight', true, 'Flexión, salto de pies al pecho y salto vertical, encadenado.'),
  ('incline-chest-press-machine', 'Press inclinado en máquina', 'chest', array['front_delt', 'triceps']::text[], 'machine', true, 'Sentado en la máquina inclinada, empuja las agarraderas hacia arriba y al frente sin bloquear los codos.'),
  ('decline-chest-press-machine', 'Press declinado en máquina', 'chest', array['triceps', 'front_delt']::text[], 'machine', true, 'En la máquina declinada empuja las agarraderas al frente y regresa controlado.'),
  ('smith-incline-press', 'Press inclinado en Smith', 'chest', array['front_delt', 'triceps']::text[], 'smith', true, 'Banca a 30 grados bajo la barra guiada, baja al pecho alto y empuja.'),
  ('smith-decline-press', 'Press declinado en Smith', 'chest', array['triceps', 'front_delt']::text[], 'smith', true, 'Banca declinada bajo la barra guiada, baja al pecho bajo y empuja.'),
  ('incline-cable-press', 'Press inclinado en polea', 'chest', array['front_delt', 'triceps']::text[], 'cable', true, 'Sentado entre poleas bajas, empuja los agarres hacia arriba y junta al frente.'),
  ('incline-cable-fly', 'Aperturas inclinadas en polea', 'chest', '{}'::text[], 'cable', false, 'En banca inclinada entre poleas, abre los brazos y júntalos sobre el pecho alto.'),
  ('single-arm-cable-crossover', 'Cruce de polea a una mano', 'chest', '{}'::text[], 'cable', false, 'De pie junto a la polea, cruza el brazo al frente apretando el pecho.'),
  ('floor-press', 'Press en el suelo con barra', 'chest', array['triceps', 'front_delt']::text[], 'barbell', true, 'Acostado en el suelo, baja la barra hasta que los codos toquen y empuja.'),
  ('db-floor-press', 'Press en el suelo con mancuernas', 'chest', array['triceps', 'front_delt']::text[], 'dumbbell', true, 'En el suelo, baja las mancuernas hasta que los codos toquen y empuja.'),
  ('wide-grip-bench-press', 'Press de banca agarre ancho', 'chest', array['front_delt', 'triceps']::text[], 'barbell', true, 'Agarre más ancho que los hombros, baja la barra al pecho y empuja.'),
  ('one-arm-db-press', 'Press de pecho a una mano', 'chest', array['triceps', 'front_delt']::text[], 'dumbbell', true, 'Acostado, empuja una sola mancuerna manteniendo el core firme.'),
  ('incline-push-up', 'Flexión inclinada', 'chest', array['triceps', 'front_delt']::text[], 'bodyweight', true, 'Manos en una superficie elevada, baja el pecho y empuja con el cuerpo recto.'),
  ('decline-push-up', 'Flexión declinada', 'chest', array['triceps', 'front_delt']::text[], 'bodyweight', true, 'Pies elevados en un banco, baja el pecho al suelo y empuja.'),
  ('wide-push-up', 'Flexión abierta', 'chest', array['front_delt']::text[], 'bodyweight', true, 'Manos bien separadas, baja el pecho al suelo y empuja.'),
  ('wide-grip-lat-pulldown', 'Jalón agarre ancho', 'back', array['biceps', 'rear_delt']::text[], 'cable', true, 'Agarre amplio, tira la barra al pecho llevando los codos abajo.'),
  ('underhand-pulldown', 'Jalón agarre supino', 'back', array['biceps', 'rear_delt']::text[], 'cable', true, 'Palmas hacia ti, tira la barra al pecho apretando la espalda.'),
  ('v-bar-pulldown', 'Jalón con triángulo', 'back', array['biceps', 'rear_delt']::text[], 'cable', true, 'Con el agarre en V, tira al pecho juntando los codos al torso.'),
  ('one-arm-lat-pulldown', 'Jalón a una mano', 'back', array['biceps', 'rear_delt']::text[], 'cable', true, 'Con un solo agarre, tira hacia abajo estirando bien el dorsal arriba.'),
  ('smith-row', 'Remo en Smith', 'back', array['biceps', 'rear_delt']::text[], 'smith', true, 'Inclinado bajo la barra guiada, tira hacia el abdomen y baja controlado.'),
  ('reverse-grip-row', 'Remo con barra supino', 'back', array['biceps', 'rear_delt']::text[], 'barbell', true, 'Agarre supino, tira la barra al abdomen con la espalda neutra.'),
  ('two-arm-db-row', 'Remo con dos mancuernas', 'back', array['biceps', 'rear_delt']::text[], 'dumbbell', true, 'Inclinado con el torso paralelo, rema ambas mancuernas al abdomen.'),
  ('seated-one-arm-cable-row', 'Remo en polea a una mano', 'back', array['biceps', 'rear_delt']::text[], 'cable', true, 'Sentado, tira el agarre a un lado del abdomen rotando ligeramente.'),
  ('leverage-high-row', 'Remo alto en máquina', 'back', array['biceps', 'rear_delt']::text[], 'machine', true, 'Pecho apoyado, tira las agarraderas hacia abajo y atrás.'),
  ('machine-shrug', 'Encogimiento en máquina', 'back', '{}'::text[], 'machine', false, 'Eleva los hombros hacia las orejas contra la resistencia y baja controlado.'),
  ('cable-shrug', 'Encogimiento en polea', 'back', '{}'::text[], 'cable', false, 'De pie frente a la polea baja, encoge los hombros sin flexionar codos.'),
  ('rope-straight-arm-pulldown', 'Pullover en polea con cuerda', 'back', array['triceps']::text[], 'cable', false, 'Brazos rectos, lleva la cuerda de arriba hacia los muslos apretando el dorsal.'),
  ('barbell-pullover', 'Pullover con barra', 'back', array['chest', 'triceps']::text[], 'barbell', false, 'Acostado, baja la barra detrás de la cabeza con codos semiflexionados y vuelve.'),
  ('weighted-pull-up', 'Dominadas con peso', 'back', array['biceps', 'rear_delt']::text[], 'bodyweight', true, 'Con peso colgado del cinturón, sube hasta superar la barra con la barbilla.'),
  ('seated-barbell-press', 'Press militar sentado', 'front_delt', array['triceps', 'lateral_delt']::text[], 'barbell', true, 'Sentado con respaldo, empuja la barra desde los hombros sobre la cabeza.'),
  ('cable-shoulder-press', 'Press de hombro en polea', 'front_delt', array['triceps', 'lateral_delt']::text[], 'cable', true, 'Sentado entre poleas bajas, empuja los agarres sobre la cabeza.'),
  ('single-arm-db-shoulder-press', 'Press de hombro a una mano', 'front_delt', array['triceps', 'lateral_delt']::text[], 'dumbbell', true, 'Empuja una sola mancuerna sobre la cabeza manteniendo el core firme.'),
  ('cable-front-raise', 'Elevación frontal en polea', 'front_delt', '{}'::text[], 'cable', false, 'Polea baja por detrás, eleva el brazo recto al frente hasta la altura del hombro.'),
  ('barbell-front-raise', 'Elevación frontal con barra', 'front_delt', '{}'::text[], 'barbell', false, 'Eleva la barra recta al frente hasta la altura de los hombros y baja.'),
  ('seated-lateral-raise', 'Elevación lateral sentado', 'lateral_delt', '{}'::text[], 'dumbbell', false, 'Sentado, eleva las mancuernas a los lados hasta la altura de los hombros.'),
  ('one-arm-side-lateral', 'Elevación lateral a una mano', 'lateral_delt', '{}'::text[], 'dumbbell', false, 'Sujeto a un soporte, eleva una mancuerna al lado con tensión controlada.'),
  ('cable-upright-row', 'Remo al mentón en polea', 'lateral_delt', array['front_delt', 'back']::text[], 'cable', true, 'Polea baja con barra, tira hacia la barbilla con los codos altos.'),
  ('db-upright-row', 'Remo al mentón con mancuernas', 'lateral_delt', array['front_delt', 'back']::text[], 'dumbbell', true, 'Tira las mancuernas hacia la barbilla con los codos por encima de las manos.'),
  ('seated-rear-delt-fly', 'Pájaros sentado', 'rear_delt', array['back']::text[], 'dumbbell', false, 'Sentado con el torso sobre los muslos, abre las mancuernas hacia los lados.'),
  ('lying-rear-delt-raise', 'Pájaros tumbado', 'rear_delt', array['back']::text[], 'dumbbell', false, 'Boca abajo en banca inclinada, eleva las mancuernas hacia los lados.'),
  ('cable-rope-rear-delt-row', 'Remo posterior con cuerda', 'rear_delt', array['back']::text[], 'cable', true, 'Polea a la altura de la cara, tira de la cuerda separando las manos.'),
  ('cable-hammer-curl', 'Curl martillo en polea', 'biceps', '{}'::text[], 'cable', false, 'Polea baja con cuerda en agarre neutro, sube hasta el hombro.'),
  ('seated-db-curl', 'Curl sentado con mancuernas', 'biceps', '{}'::text[], 'dumbbell', false, 'Sentado, sube las mancuernas sin balancear el torso.'),
  ('alternating-db-curl', 'Curl alterno con mancuernas', 'biceps', '{}'::text[], 'dumbbell', false, 'Sube una mancuerna a la vez alternando los brazos.'),
  ('zottman-curl', 'Curl Zottman', 'biceps', '{}'::text[], 'dumbbell', false, 'Sube en supinación y baja en pronación rotando arriba.'),
  ('drag-curl', 'Curl drag', 'biceps', '{}'::text[], 'barbell', false, 'Lleva los codos atrás arrastrando la barra pegada al cuerpo.'),
  ('cross-body-hammer-curl', 'Curl martillo cruzado', 'biceps', '{}'::text[], 'dumbbell', false, 'Sube la mancuerna en diagonal hacia el hombro contrario.'),
  ('cable-preacher-curl', 'Curl predicador en polea', 'biceps', '{}'::text[], 'cable', false, 'Brazos apoyados en el banco predicador, sube con la polea baja.'),
  ('machine-preacher-curl', 'Curl predicador en máquina', 'biceps', '{}'::text[], 'machine', false, 'Brazos sobre la almohadilla, flexiona los codos contra la resistencia.'),
  ('wide-grip-barbell-curl', 'Curl con barra agarre ancho', 'biceps', '{}'::text[], 'barbell', false, 'Agarre más ancho que los hombros, sube sin balancear.'),
  ('v-bar-pushdown', 'Extensión en polea con barra V', 'triceps', '{}'::text[], 'cable', false, 'Codos pegados al torso, extiende empujando la barra V hacia abajo.'),
  ('reverse-grip-pushdown', 'Extensión en polea agarre inverso', 'triceps', '{}'::text[], 'cable', false, 'Palmas hacia arriba, extiende el brazo manteniendo el codo fijo.'),
  ('single-arm-pushdown', 'Extensión en polea a una mano', 'triceps', '{}'::text[], 'cable', false, 'Con un agarre, extiende el brazo manteniendo el codo pegado al cuerpo.'),
  ('ez-skull-crusher', 'Press francés con barra Z', 'triceps', '{}'::text[], 'barbell', false, 'Acostado, baja la barra Z a la frente flexionando solo los codos.'),
  ('db-skull-crusher', 'Press francés con mancuernas', 'triceps', '{}'::text[], 'dumbbell', false, 'Acostado, baja las mancuernas a los lados de la cabeza y extiende.'),
  ('seated-db-triceps-press', 'Press francés sentado', 'triceps', '{}'::text[], 'dumbbell', false, 'Sentado, baja una mancuerna detrás de la cabeza y extiende arriba.'),
  ('dip-machine', 'Fondos en máquina', 'triceps', array['chest', 'front_delt']::text[], 'machine', true, 'Empuja las agarraderas hacia abajo extendiendo los codos.'),
  ('parallel-bar-dip', 'Fondos en paralelas (tríceps)', 'triceps', array['chest', 'front_delt']::text[], 'bodyweight', true, 'Torso vertical, baja flexionando codos y empuja hasta extender.'),
  ('close-grip-db-press', 'Press cerrado con mancuernas', 'triceps', array['chest', 'front_delt']::text[], 'dumbbell', true, 'Mancuernas juntas sobre el pecho, baja y empuja con los codos cerrados.'),
  ('smith-close-grip-press', 'Press cerrado en Smith', 'triceps', array['chest', 'front_delt']::text[], 'smith', true, 'Manos al ancho de hombros bajo la barra guiada, baja al pecho y empuja.'),
  ('standing-overhead-barbell-extension', 'Extensión sobre cabeza con barra', 'triceps', '{}'::text[], 'barbell', false, 'De pie, baja la barra detrás de la cabeza y extiende los brazos arriba.'),
  ('box-squat', 'Sentadilla en caja', 'quads', array['glutes', 'hamstrings']::text[], 'barbell', true, 'Baja hasta sentarte brevemente en la caja y empuja para subir.'),
  ('dumbbell-squat', 'Sentadilla con mancuernas', 'quads', array['glutes', 'hamstrings']::text[], 'dumbbell', true, 'Mancuernas a los lados, baja hasta paralelo y empuja con los talones.'),
  ('barbell-lunge', 'Zancada con barra', 'quads', array['glutes', 'hamstrings']::text[], 'barbell', true, 'Barra en la espalda, da un paso al frente y baja hasta 90 grados.'),
  ('reverse-lunge', 'Zancada inversa', 'quads', array['glutes', 'hamstrings']::text[], 'dumbbell', true, 'Da un paso hacia atrás y baja la rodilla cerca del suelo.'),
  ('barbell-walking-lunge', 'Zancada caminando con barra', 'quads', array['glutes', 'hamstrings']::text[], 'barbell', true, 'Con la barra en la espalda, avanza alternando zancadas.'),
  ('narrow-stance-leg-press', 'Prensa pies juntos', 'quads', array['glutes']::text[], 'machine', true, 'Pies juntos y bajos en la plataforma, baja controlado y empuja.'),
  ('single-leg-extension', 'Extensión de cuádriceps a una pierna', 'quads', '{}'::text[], 'machine', false, 'Extiende una rodilla a la vez contra la resistencia, pausa arriba.'),
  ('barbell-step-up', 'Subida al cajón con barra', 'quads', array['glutes', 'hamstrings']::text[], 'barbell', true, 'Con la barra en la espalda, sube al cajón empujando con la pierna de arriba.'),
  ('plie-squat', 'Sentadilla plié', 'quads', array['glutes', 'hamstrings']::text[], 'dumbbell', true, 'Pies anchos y puntas afuera, baja con una mancuerna entre las piernas.'),
  ('standing-leg-curl', 'Curl femoral de pie', 'hamstrings', '{}'::text[], 'machine', false, 'Flexiona una rodilla a la vez llevando el talón al glúteo.'),
  ('single-leg-rdl', 'Peso muerto rumano a una pierna', 'hamstrings', array['glutes', 'back']::text[], 'dumbbell', true, 'Sobre una pierna, baja la mancuerna con cadera atrás y sube.'),
  ('reverse-hyperextension', 'Hiperextensión inversa', 'hamstrings', array['glutes']::text[], 'machine', false, 'Torso fijo en el banco, eleva las piernas atrás apretando glúteo e isquios.'),
  ('smith-stiff-leg-deadlift', 'Peso muerto rígido en Smith', 'hamstrings', array['glutes', 'back']::text[], 'smith', true, 'Piernas casi rectas, baja la barra guiada estirando los isquios.'),
  ('barbell-glute-bridge', 'Puente de glúteo con barra', 'glutes', array['hamstrings']::text[], 'barbell', true, 'En el suelo con la barra en la cadera, eleva apretando el glúteo arriba.'),
  ('single-leg-glute-bridge', 'Puente de glúteo a una pierna', 'glutes', array['hamstrings']::text[], 'bodyweight', false, 'Una pierna extendida, eleva la cadera con la otra apretando el glúteo.'),
  ('glute-kickback', 'Patada de glúteo', 'glutes', array['hamstrings']::text[], 'bodyweight', false, 'En cuadrupedia, extiende una pierna hacia atrás y arriba.'),
  ('donkey-calf-raise', 'Gemelo burro', 'calves', '{}'::text[], 'machine', false, 'Inclinado hacia adelante con peso en la cadera, eleva los talones al máximo.'),
  ('db-standing-calf-raise', 'Gemelo de pie con mancuerna', 'calves', '{}'::text[], 'dumbbell', false, 'Punta en un escalón con una mancuerna, eleva el talón y baja profundo.'),
  ('reverse-crunch', 'Crunch inverso', 'core', '{}'::text[], 'bodyweight', false, 'Acostado, lleva las rodillas al pecho elevando la cadera del suelo.'),
  ('cable-woodchopper', 'Leñador en polea', 'core', '{}'::text[], 'cable', false, 'De lado a la polea alta, baja en diagonal cruzando el cuerpo.'),
  ('captains-chair-leg-raise', 'Elevación de piernas en paralelas', 'core', '{}'::text[], 'bodyweight', false, 'Apoyado en los antebrazos, eleva las piernas controladas al frente.'),
  ('sit-up', 'Abdominal completo', 'core', '{}'::text[], 'bodyweight', false, 'Pies fijos, sube el torso completo y baja controlado.'),
  ('cable-russian-twist', 'Giro ruso en polea', 'core', '{}'::text[], 'cable', false, 'Sentado o de pie, rota el torso contra la polea de lado a lado.'),
  ('weighted-side-bend', 'Inclinación lateral con mancuerna', 'core', '{}'::text[], 'dumbbell', false, 'Mancuerna a un lado, inclina el torso lateralmente y vuelve.'),
  ('v-up', 'V-up', 'core', '{}'::text[], 'bodyweight', false, 'Sube tronco y piernas a la vez tocando los pies formando una V.'),
  ('oblique-crunch', 'Crunch oblicuo', 'core', '{}'::text[], 'bodyweight', false, 'Acostado de lado, eleva el torso contrayendo los oblicuos.')
on conflict (id) do update set
  name = excluded.name,
  muscle_group = excluded.muscle_group,
  secondary_muscles = excluded.secondary_muscles,
  equipment = excluded.equipment,
  is_compound = excluded.is_compound,
  instructions = excluded.instructions;
