/**
 * Static require map for bundled exercise demonstration images.
 *
 * React Native's Metro bundler only resolves `require()` calls with literal
 * string paths, so each asset must be listed explicitly here (no dynamic
 * `require(`...${id}`)`). Images are optimized WebP (~17 KB each) generated by
 * `scripts/fetch-exercise-images.mjs` from the public-domain free-exercise-db.
 *
 * Keys match Exercise.id in `@/data/exercises`.
 */

const EXERCISE_IMAGES: Record<string, number> = {
  'bench-press': require('../../assets/exercises/bench-press.webp'),
  'incline-db-press': require('../../assets/exercises/incline-db-press.webp'),
  'cable-fly': require('../../assets/exercises/cable-fly.webp'),
  'pull-up': require('../../assets/exercises/pull-up.webp'),
  'barbell-row': require('../../assets/exercises/barbell-row.webp'),
  'lat-pulldown': require('../../assets/exercises/lat-pulldown.webp'),
  'face-pull': require('../../assets/exercises/face-pull.webp'),
  'deadlift': require('../../assets/exercises/deadlift.webp'),
  'overhead-press': require('../../assets/exercises/overhead-press.webp'),
  'lateral-raise': require('../../assets/exercises/lateral-raise.webp'),
  'rear-delt-fly': require('../../assets/exercises/rear-delt-fly.webp'),
  'biceps-curl': require('../../assets/exercises/biceps-curl.webp'),
  'hammer-curl': require('../../assets/exercises/hammer-curl.webp'),
  'triceps-pushdown': require('../../assets/exercises/triceps-pushdown.webp'),
  'skull-crusher': require('../../assets/exercises/skull-crusher.webp'),
  'squat': require('../../assets/exercises/squat.webp'),
  'leg-press': require('../../assets/exercises/leg-press.webp'),
  'lunges': require('../../assets/exercises/lunges.webp'),
  'romanian-deadlift': require('../../assets/exercises/romanian-deadlift.webp'),
  'leg-curl': require('../../assets/exercises/leg-curl.webp'),
  'hip-thrust': require('../../assets/exercises/hip-thrust.webp'),
  'standing-calf': require('../../assets/exercises/standing-calf.webp'),
  'plank': require('../../assets/exercises/plank.webp'),
  'hanging-leg-raise': require('../../assets/exercises/hanging-leg-raise.webp'),
};

/** Bundled demonstration image for an exercise id, or undefined if none. */
export function exerciseImage(id: string): number | undefined {
  return EXERCISE_IMAGES[id];
}
